In [5]:
from tqdm import tqdm
import pandas as pd
import json
import os
import numpy as np

In [6]:
# All downloaded files 
os.listdir("downloads")

['2006.json',
 '2007.json',
 '2008.json',
 '2009.json',
 '2010.json',
 '2011.json',
 '2012.json',
 '2013.json',
 '2014.json',
 '2015.json',
 '2016.json',
 '2017.json',
 '2018.json',
 '2019.json']

## Utforskande analys 

Vi börjar med att kolla på 2019, då vi tidigt såg att 2019 hade bäst data

In [7]:
def open_file(filename):
    with open(filename) as f:
        output = json.loads(f.read())
        
    return output

af_19 = open_file("./downloads/2006.json")

In [8]:
af_19[0]

{'access': None,
 'access_to_own_car': None,
 'application_deadline': '2006-05-16',
 'application_details': {'email': None,
  'information': None,
  'other': None,
  'reference': None,
  'url': None,
  'via_af': None},
 'description': {'company_information': None,
  'conditions': 'heltid/deltid/begränsad tid',
  'needs': None,
  'requirements': None,
  'text': 'Medrek Rekrytering AB söker på uppdrag av Manpower Helse sjuksköterskor med grundutbildning och av alla specialiteter till arbete i Oslo och övriga Norge över sommaren!   Manpower Helse är Norges ledande bemanningsföretag vilket är tryggt för dig.Inte minst erbjuder Manpower Helse väldigt goda möjligheter till många arbetstimmar och även övertid och helgarbete  Du erbjuds: -Hög lön  -Bra tillägg vid övertid, kvälls och helgarbete -betald resa -centralt boende  Den 22 och 23 maj hålls intervjuer med sjuksköterskor i Stockholm.   Anmäl ditt intresse för att komma omgående genom att klicka på följande länk: http://www.medrek.se/run/?_sid=1&form=medrek&annonsid=86835      Ju fler veckor du är intresserad av att jobba för Manpower Helse i Norge ju större chans har du att få arbete.Speca därför i din ansökan hur många veckor du vill jobba.',
  'text_formatted': None},
 'driving_license': None,
 'driving_license_required': None,
 'duration': {'concept_id': None,
  'label': '11 dagar - 3 månader',
  'legacy_ams_taxonomy_id': None},
 'employer': {'email': None,
  'name': 'Medrek Rekrytering AB',
  'organization_number': None,
  'phone_number': None,
  'url': None,
  'workplace': None},
 'employment_type': {'concept_id': None,
  'label': None,
  'legacy_ams_taxonomy_id': None},
 'experience_required': None,
 'external_id': None,
 'headline': 'Jobba i Norge med Manpower Helse!',
 'id': None,
 'last_publication_date': '2006-05-16',
 'logo_url': None,
 'must_have': {'languages': None, 'skills': None, 'work_experiences': None},
 'nice_to_have': {'languages': None, 'skills': None, 'work_experiences': None},
 'number_of_vacancies': '1',
 'occupation': {'concept_id': None,
  'label': None,
  'legacy_ams_taxonomy_id': '5780'},
 'occupation_field': {'concept_id': None,
  'label': None,
  'legacy_ams_taxonomy_id': None},
 'occupation_group': {'concept_id': None,
  'label': None,
  'legacy_ams_taxonomy_id': None},
 'publication_date': '2006-05-11',
 'removed': None,
 'removed_date': None,
 'salary_description': None,
 'salary_type': {'concept_id': None,
  'label': None,
  'legacy_ams_taxonomy_id': None},
 'scope_of_work': {'max': None, 'min': None},
 'source_type': None,
 'timestamp': None,
 'webpage_url': None,
 'working_hours_type': {'concept_id': None,
  'label': 'Heltid/Deltid',
  'legacy_ams_taxonomy_id': None},
 'workplace_address': {'city': 'STOCKHOLM',
  'coordinates': None,
  'country': None,
  'country_code': None,
  'country_concept_id': None,
  'municipality': None,
  'municipality_code': None,
  'municipality_concept_id': None,
  'postcode': None,
  'region': None,
  'region_code': None,
  'region_concept_id': None,
  'street_address': None},
 'other_old_legacy_attributes': {'ARBETSDRIFT': 'Dagtid',
  'DXA': None,
  'BIL_KRAV': None,
  'TILLTRADE': None}}

In [9]:
af_19_df = pd.DataFrame(af_19)

In [10]:
af_19_df.sample(5)

,access,access_to_own_car,application_deadline,application_details,description,driving_license,driving_license_required,duration,employer,employment_type,...,removed_date,salary_description,salary_type,scope_of_work,source_type,timestamp,webpage_url,working_hours_type,workplace_address,other_old_legacy_attributes
103174,None,None,2006-09-08,"{'email': None, 'information': None, 'other': ...","{'company_information': None, 'conditions': 'V...",None,None,"{'concept_id': None, 'label': 'Tills vidare', ...","{'email': None, 'name': 'Allers Förlag AB', 'o...","{'concept_id': None, 'label': None, 'legacy_am...",...,None,None,"{'concept_id': None, 'label': None, 'legacy_am...","{'max': None, 'min': None}",None,None,None,"{'concept_id': None, 'label': 'Heltid/Deltid',...","{'city': 'Helsingborg', 'coordinates': None, '...","{'ARBETSDRIFT': 'Dagtid', 'DXA': None, 'BIL_KR..."
238328,None,None,2006-12-14,"{'email': None, 'information': None, 'other': ...","{'company_information': None, 'conditions': 'B...",None,None,"{'concept_id': None, 'label': 'Tills vidare', ...","{'email': None, 'name': 'Apoteket AB', 'organi...","{'concept_id': None, 'label': None, 'legacy_am...",...,None,None,"{'concept_id': None, 'label': None, 'legacy_am...","{'max': None, 'min': None}",None,None,None,"{'concept_id': None, 'label': 'Heltid', 'legac...","{'city': 'STOCKHOLM', 'coordinates': None, 'co...","{'ARBETSDRIFT': 'Dagtid', 'DXA': None, 'BIL_KR..."
127712,None,None,2006-03-05,"{'email': None, 'information': None, 'other': ...","{'company_information': None, 'conditions': 'V...",None,None,"{'concept_id': None, 'label': 'Längre än 6 mån...","{'email': None, 'name': 'Proffice Sverige AB/G...","{'concept_id': None, 'label': None, 'legacy_am...",...,None,None,"{'concept_id': None, 'label': None, 'legacy_am...","{'max': None, 'min': None}",None,None,None,"{'concept_id': None, 'label': 'Heltid', 'legac...","{'city': 'GÖTEBORG', 'coordinates': None, 'cou...","{'ARBETSDRIFT': 'Dagtid', 'DXA': None, 'BIL_KR..."
226968,None,None,2006-05-24,"{'email': None, 'information': None, 'other': ...","{'company_information': None, 'conditions': 'T...",None,None,"{'concept_id': None, 'label': 'Tills vidare', ...","{'email': None, 'name': 'SCANDIC ÖRNSKÖLDSVIK'...","{'concept_id': None, 'label': None, 'legacy_am...",...,None,None,"{'concept_id': None, 'label': None, 'legacy_am...","{'max': None, 'min': None}",None,None,None,"{'concept_id': None, 'label': 'Heltid', 'legac...","{'city': None, 'coordinates': None, 'country':...","{'ARBETSDRIFT': 'Schemalagd arbetstid', 'DXA':..."
196404,None,None,2006-04-03,"{'email': None, 'information': None, 'other': ...","{'company_information': None, 'conditions': 'S...",None,None,"{'concept_id': None, 'label': '11 dagar - 3 må...","{'email': None, 'name': 'SÖDERBÄRKE FÖRSAMLING...","{'concept_id': None, 'label': None, 'legacy_am...",...,None,None,"{'concept_id': None, 'label': None, 'legacy_am...","{'max': None, 'min': None}",None,None,None,"{'concept_id': None, 'label': 'Deltid', 'legac...","{'city': None, 'coordinates': None, 'country':...","{'ARBETSDRIFT': 'Schemalagd arbetstid', 'DXA':..."

In [11]:
af_19_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 245227 entries, 0 to 245226
Data columns (total 34 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   access                       0 non-null       object
 1   access_to_own_car            0 non-null       object
 2   application_deadline         245227 non-null  object
 3   application_details          245227 non-null  object
 4   description                  245227 non-null  object
 5   driving_license              0 non-null       object
 6   driving_license_required     0 non-null       object
 7   duration                     245227 non-null  object
 8   employer                     245227 non-null  object
 9   employment_type              245227 non-null  object
 10  experience_required          0 non-null       object
 11  external_id                  0 non-null       object
 12  headline                     245225 non-null  object
 13  id                           17 non-null      object
 14  last_publication_date        245227 non-null  object
 15  logo_url                     0 non-null       object
 16  must_have                    245227 non-null  object
 17  nice_to_have                 245227 non-null  object
 18  number_of_vacancies          245227 non-null  object
 19  occupation                   245227 non-null  object
 20  occupation_field             245227 non-null  object
 21  occupation_group             245227 non-null  object
 22  publication_date             245227 non-null  object
 23  removed                      0 non-null       object
 24  removed_date                 0 non-null       object
 25  salary_description           0 non-null       object
 26  salary_type                  245227 non-null  object
 27  scope_of_work                245227 non-null  object
 28  source_type                  0 non-null       object
 29  timestamp                    0 non-null       object
 30  webpage_url                  0 non-null       object
 31  working_hours_type           245227 non-null  object
 32  workplace_address            245227 non-null  object
 33  other_old_legacy_attributes  245227 non-null  object
dtypes: object(34)
memory usage: 63.6+ MB

Vi vill gärna expandera columner som är nested-dicts

In [13]:
def expand_dict(df, col_name):
    
    if type(df[col_name].values[0]) == dict:
        col_df = pd.DataFrame(df[col_name].values.tolist())
        names = {name: col_name + "_" + name for name in list(col_df)}
        col_df = col_df.rename(names, axis=1)
        return col_df
    else:
        return None
    
def expand_cols(df_r):
    df = df_r.copy()
    old_cols = []
    while old_cols != list(df):
        old_cols = list(df)
        for col_name in list(df):
            col_df = expand_dict(df, col_name)
            if col_df is not None:
                df[list(col_df)] = col_df
                df = df.drop(col_name, axis = 1)
    return df

df = expand_cols(af_19_df)
df

,access,access_to_own_car,application_deadline,driving_license,driving_license_required,experience_required,external_id,headline,id,last_publication_date,...,workplace_address_municipality_concept_id,workplace_address_postcode,workplace_address_region,workplace_address_region_code,workplace_address_region_concept_id,workplace_address_street_address,other_old_legacy_attributes_ARBETSDRIFT,other_old_legacy_attributes_DXA,other_old_legacy_attributes_BIL_KRAV,other_old_legacy_attributes_TILLTRADE
0,None,None,2006-05-16,None,None,None,None,Jobba i Norge med Manpower Helse!,None,2006-05-16,...,None,None,None,None,None,None,Dagtid,None,None,None
1,None,None,2006-07-01,None,None,None,None,Au Pair i Rom,None,2006-07-01,...,None,None,None,None,None,None,Dagtid,None,None,None
2,None,None,2006-07-14,None,None,None,None,Teknisk chef,None,2006-07-14,...,None,None,None,None,None,None,Dagtid,None,None,None
3,None,None,2006-08-30,None,None,None,None,OPERASJONSSYKEPLEIERE TIL NORGE,None,2006-08-30,...,None,None,None,None,None,None,Dagtid,None,None,None
4,None,None,2006-07-31,None,None,None,None,Jobba som värvare för Greenpeace!,None,2006-07-31,...,None,None,None,None,None,None,Dagtid,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245222,None,None,2006-10-01,None,None,None,None,InternannonsAdministratör till Teknisk Avdelning,None,2006-10-01,...,None,None,None,None,None,None,Dagtid,None,None,None
245223,None,None,2006-01-20,None,None,None,None,Generalsekreterarassistent,None,2006-01-20,...,None,None,None,None,None,None,Dagtid,None,None,None
245224,None,None,2006-04-18,None,None,None,None,Butikspersonal,None,2006-04-18,...,None,None,None,None,None,None,Dagtid,None,None,None
245225,None,None,2006-04-30,None,None,None,None,Friår:Fordonstekniker,None,2006-04-30,...,None,None,None,None,None,None,Dagtid,None,None,None
245226,None,None,2006-08-05,None,None,None,None,"Projektingenjör, hydraulikingenjör",None,2006-08-05,...,None,None,None,None,None,None,Dagtid,None,None,None

In [14]:
high_na = (df.isna().sum() >= int(df.shape[0]*4/5))

na_cols = list(high_na[high_na == True].index)
print(na_cols)
print(len(na_cols))

['access', 'access_to_own_car', 'driving_license', 'driving_license_required', 'experience_required', 'external_id', 'id', 'logo_url', 'removed', 'removed_date', 'salary_description', 'source_type', 'timestamp', 'webpage_url', 'application_details_email', 'application_details_information', 'application_details_other', 'application_details_reference', 'application_details_url', 'application_details_via_af', 'description_company_information', 'description_needs', 'description_requirements', 'description_text_formatted', 'duration_concept_id', 'duration_legacy_ams_taxonomy_id', 'employer_email', 'employer_organization_number', 'employer_phone_number', 'employer_url', 'employer_workplace', 'employment_type_concept_id', 'employment_type_label', 'employment_type_legacy_ams_taxonomy_id', 'must_have_languages', 'must_have_skills', 'must_have_work_experiences', 'nice_to_have_languages', 'nice_to_have_skills', 'nice_to_have_work_experiences', 'occupation_concept_id', 'occupation_label', 'occupation_field_concept_id', 'occupation_field_label', 'occupation_field_legacy_ams_taxonomy_id', 'occupation_group_concept_id', 'occupation_group_label', 'occupation_group_legacy_ams_taxonomy_id', 'salary_type_concept_id', 'salary_type_label', 'salary_type_legacy_ams_taxonomy_id', 'scope_of_work_max', 'scope_of_work_min', 'working_hours_type_concept_id', 'working_hours_type_legacy_ams_taxonomy_id', 'workplace_address_coordinates', 'workplace_address_country', 'workplace_address_country_code', 'workplace_address_country_concept_id', 'workplace_address_municipality', 'workplace_address_municipality_concept_id', 'workplace_address_postcode', 'workplace_address_region', 'workplace_address_region_code', 'workplace_address_region_concept_id', 'workplace_address_street_address', 'other_old_legacy_attributes_DXA', 'other_old_legacy_attributes_BIL_KRAV', 'other_old_legacy_attributes_TILLTRADE']
69

In [15]:
df = df.drop(na_cols, axis = 1) # more than 4/5 are None

In [16]:
df

,application_deadline,headline,last_publication_date,number_of_vacancies,publication_date,description_conditions,description_text,duration_label,employer_name,occupation_legacy_ams_taxonomy_id,working_hours_type_label,workplace_address_city,workplace_address_municipality_code,other_old_legacy_attributes_ARBETSDRIFT
0,2006-05-16,Jobba i Norge med Manpower Helse!,2006-05-16,1,2006-05-11,heltid/deltid/begränsad tid,Medrek Rekrytering AB söker på uppdrag av Manp...,11 dagar - 3 månader,Medrek Rekrytering AB,5780,Heltid/Deltid,STOCKHOLM,None,Dagtid
1,2006-07-01,Au Pair i Rom,2006-07-01,1,2006-05-10,28 timmar per vecka. Barnvakt 1-2 kvällar per ...,Familj med tre barn; två tjejer och en kille p...,Längre än 6 månader,Work & Study Abroad Stockholm,5552,Deltid,STOCKHOLM,None,Dagtid
2,2006-07-14,Teknisk chef,2006-07-14,1,2006-06-22,Heltid/Tillsvidare,Din uppgift blir att tillsammans med medarbeta...,Tills vidare,Kalix kommun,5434,Heltid,KALIX,2514,Dagtid
3,2006-08-30,OPERASJONSSYKEPLEIERE TIL NORGE,2006-08-30,50,2006-07-11,100% stilling,Vi har behov for operasjonssykepleiere til lan...,3-6 månader,Poolia Vård AB,5781,Heltid,None,None,Dagtid
4,2006-07-31,Jobba som värvare för Greenpeace!,2006-07-31,6,2006-07-18,"6 timmar om dagen mellan 11 och 18, mån-fre va...",Detta är det perfekta jobbet ! Arbetstiderna ä...,11 dagar - 3 månader,Greenpeace Norden,7160,Deltid,STOCKHOLM,2480,Dagtid
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245222,2006-10-01,InternannonsAdministratör till Teknisk Avdelning,2006-10-01,1,2006-09-20,Provanställning.,INTERNANNONS \r\nAdministratör till teknisk av...,Tills vidare,Arenco AB,0,Heltid,None,0880,Dagtid
245223,2006-01-20,Generalsekreterarassistent,2006-01-20,1,2006-01-03,Heltids projektanställning till den 1 februari...,Vi söker en generalsekreterarassistent. Tjänst...,Längre än 6 månader,Svenska FN-Förbundet,0,Heltid,STOCKHOLM,0180,Dagtid
245224,2006-04-18,Butikspersonal,2006-04-18,1,2006-04-04,Butikstider ned tjänstgöring varannan helg.,Engagerad personal sökes. En av våra medarbet...,Längre än 6 månader,BABY PLANET,0,Heltid,STOCKHOLM,0180,Dagtid
245225,2006-04-30,Friår:Fordonstekniker,2006-04-30,0,2006-02-28,None,Friårsvikariat\r\nObs! anvisa ej\r\nFordonsrep...,3-6 månader,"Kalmar kommun, Fastighets- och inköpskontoret",0,Heltid,None,0880,Dagtid
245226,2006-08-05,"Projektingenjör, hydraulikingenjör",2006-08-05,5,2006-07-06,Tillsvidare/Heltid,Bemannus Personalpartner AB är ett företag som...,Tills vidare,Bemannus Personalpartner AB,0,Heltid,HISINGS BACKA,None,Dagtid

Vi behöver även fixa time-stamps

In [17]:
ts_cols = ['application_deadline', 'last_publication_date', 'publication_date']

In [18]:
df['application_deadline'] = pd.to_datetime(df['application_deadline'], errors='coerce')

In [19]:
df['last_publication_date'] = pd.to_datetime(df['last_publication_date'], errors='coerce')

In [20]:
df['publication_date'] = pd.to_datetime(df['publication_date'], errors='coerce')

### Save our df to hdf

In [21]:
df.head(0).to_csv('af_prepro.csv', encoding='ISO-8859-1')

In [22]:
def append_iter_csv(df, name):
    chunks = int(df.shape[0] / 1000)
    for chunk in tqdm(np.array_split(df, chunks)):
        chunk.to_csv(name, mode='a', header=False, encoding='ISO-8859-1')
        
append_iter_csv(df, 'af_prepro.csv')

100%|██████████| 245/245 [00:14<00:00, 16.56it/s]